ingress:
  enabled: false
resources:
  requests:
    memory: "1Gi"
  limits:
    memory: "4Gi"
image:
  tag: latest
  pullPolicy: Always

publicUrl: https://eoapi.apx.develop.eoepca.org/manage/
stacApi: https://eoapi.apx.develop.eoepca.org/stac/
