apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-catalogue-v2
  namespace: argocd
  labels:
    eoepca/app-name: resource-catalogue
spec:
  project: eoepca
  source:
    repoURL: 'https://eoepca.github.io/helm-charts-dev'
    chart: rm-resource-catalogue
    targetRevision: 2.0.0-dev5
    helm:
      releaseName: resource-catalogue
      valuesObject:
        global:
          namespace: resource-registration
        ingress:
          enabled: false
        db:
          volume_storage_type: managed-nfs-storage-retain
        pycsw:
          image:
            # repository: geopython/pycsw
            tag: "eoepca-staging"
            pullPolicy: Always
          config:
            server:
              url: https://resource-registration.develop.eoepca.org/catalogue
            manager:
              transactions: "true"
              allowed_ips:
                - '"*"'
            metadata:
              identification:
                title: EOEPCA+ Resource Catalogue
                description: EOEPCA+ Resource Catalogue
                keywords:
                    - EOEPCA+
                    - Earth observation
                    - discovery
                license:
                  name: CC-BY 4.0 license
                  url: https://creativecommons.org/licenses/by/4.0
                keywords_type: theme
                terms_of_service: https://creativecommons.org/licenses/by/4.0
                url: https://eoepca.org
              provider:
                name: EOEPCA+
                url: https://eoepca.org/
            repository:
              facets:
                  - type
  destination:
    name: in-cluster
    namespace: resource-registration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
