apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-api-v2
  namespace: argocd
  labels:
    eoepca/app-name: registration-api
spec:
  project: eoepca
  source:
    repoURL: 'https://eoepca.github.io/helm-charts-dev'
    chart: registration-api
    targetRevision: 2.0.0-beta2
    helm:
      releaseName: registration-api
      valuesObject:
        global:
          namespace: resource-registration
        ingress:
          enabled: false
        pygeoapi:
          image:
            repository: eoepca/registration-api
            pullPolicy: Always
            tag: "latest"
          config:
            server:
              url: https://resource-registration.apx.develop.eoepca.org
            logging:
              level: ERROR
              # /tmp/pygeoapi.log
            metadata:
              identification:
                title: EOEPCA+ Registration API
                description: EOEPCA+ Registration API
                keywords:
                    - EOEPCA+
                    - Earth observation
                    - exploitation
                    - processing
                    - registration
                keywords_type: theme
                terms_of_service: https://creativecommons.org/licenses/by/4.0
                url: https://eoepca.org
              license:
                name: CC-BY 4.0 license
                url: https://creativecommons.org/licenses/by/4.0
              provider:
                name: EOEPCA+
                url: https://eoepca.org
            resources:
              register:
                type: process
                processor:
                  name: registration_api.processes.registration.RegisterProcessor
              deregister:
                type: process
                processor:
                  name: registration_api.processes.registration.DeregisterProcessor
              hello-world:
                type: process
                processor:
                  name: HelloWorld

  destination:
    name: in-cluster
    namespace: resource-registration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
