apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata: 
  name: resource-registration
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    realmId: eoepca
    name: resource-registration
    accessType: PUBLIC
    clientId: resource_registration
    standardFlowEnabled: true
    implicitFlowEnabled: true
    directAccessGrantsEnabled: true # allow for now to simplify testing
    serviceAccountsEnabled: false
    oauth2DeviceAuthorizationGrantEnabled: true    
    rootUrl: https://resource-registration.develop.eoepca.org
    webOrigins: 
      - '/*'
    validRedirectUris:
      - '/*'
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata: 
  name: records-editor
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    realmId: eoepca
    name: records_editor
    clientIdRef:
      name: resource-registration
      policy:
        resolution: Required
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata: 
  name: resource-registration-admin
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    realmId: eoepca
    name: resource-registration-admin    
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata: 
  name: resource-registration-admin
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    realmId: eoepca
    groupIdRef:
      name: resource-registration-admin
      policy:
        resolution: Required
    roleIdsRefs:
      - name: records-editor
        policy:
          resolution: Required
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata: 
  name: resource-registration-admin
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    groupIdRef:
      name: resource-registration-admin
      policy:
        resolution: Required
    members:
    - example-admin
    - example-user-1 # for demo purposes add example-user1 but not example-user2 to resource-registration-admin group
    realmId: eoepca