apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: application-quality-auth-client
  namespace: application-quality
spec:
  encryptedData:
    OIDC_RP_CLIENT_ID: AgCjTfXwaWFvQKyU0k/bVLeL0nX5eTal3pzK9iTdwGyoiFYQPQdkZiljM3s8IVEoZx3Z+67BMWZW5HTV28WikUv1V6uV3we1J34uDG3gP0XWF7VmidZHttEKyqRNusIifuIl6vu4E54NVxRVWBUuqEJd9RxMqD+eV05mVqwg7zYR85V7h32HGFbvM0kwoxNwHIUadp7aLPSjrDHB0CYrVV9b1N7NTAa/JSb8ItDl2k4P7Ft5Wj4y64pky2nIipEoCiQqxE5Wmf+lLkBYQlBLlxBLCLlHkFUvpVCg1oWhR2ILGKS1cYdTOgKlRyz17jnC7ht9H8XGqG4LsgRWmxdankujS6LetdS1rjc6y728M0v6MF9ETPeA1DeTGYW9+mE0nHTVSe1KYBbmfwbM7m5UDjNghFYjm/AnHNXKGXkGG2AU4CuKdgigMmDzIgvTu5q230ipH+v6gffZLIK8o1S6/0jXk19EJS/trrpvSlomssaQVfsaSU46r1Uq+LU8wWgXSRjqVxzKV5ihPattzs4VsX/SgRrhaFxfOmFlkEmdRKApnd825/an1MyfYzLvC+Z0RNw33sY/dpuLpgn9DFj5zqaMfFIFq70xLlfso/6x2mcYWFh7TriTSC+BY3CgZrhS8VQLbuUtkBzw8UVJ4UTXZ2y6b4uKflwnpNMBNG0S1faW7RxP4SIIv5p+n4WZe1V6v0bdQQc5tt3AJwBMvccI/PlpJL+pTrfeWS/fBLc=
    OIDC_RP_CLIENT_SECRET: AgBRGgVa8u8WrK25mru6LkApJnkDUvj7LU9TTOm1rkUv5s1yiqEZnmw+aeBWgAkCd7mg7p7NSI+SjnX/yu3GKl6UlgdxQbXF0XqNvhQwbUJmL9KeDW3HKenGFBigYKhRzEm/5k9JL7wQhQ75jf6wjPJi4anxV1KXxu3Pi7TvcwjhWVMdQ5DwkoDAyYdxZy/UpT7v5ANkHxP1+5HswKRorhSZbTqcxa/ytV7ZNO8mrW4w2otFdCshAPZ5sbw9xoQnN6DTi0DgJ/OjUn7eqNqTiWpk1PvhLrvOfcFGUUZiocUPOqHe/d+6n8xf9AjrKDYoq2ghsMSbotgzOlSob7VxD+VcZNqpRDyZ5QZqOVua+B1rNAizLbyda9tmiuf13Dl3u0cHT815mQ7yFzAetq4WUmeM1/G8PlZPTuSdr20X5ooSKOg+YaBHXsxIB072IuDenq+gMqaNchluDlSsqcsSfYboGffLvLLRXiM3Ano3oGGtkNAobvYRGzyb40bCXFsWNUw5KimKNb8kCFoXkDJt4IFP+tCgPG7xXB8Mzh359og1r8sEYSNLri2eiJm6bbx3GtrQLWCADvNUMB5it+NjUp0+4fM1+PH3VfKUat1Zn3v6qlNIezbLVIwGJMhj7IqCAeu75F4CqkwbpEsTRsEIqEVFpxVTnxl0T+GziWIKXa3TKcvReRXdmMsSnZlmIl52dFb11Ov5p92JHy/SWfVRwFN2zge2sDm9vzfg9hIHLHy6vw==
  template:
    metadata:
      creationTimestamp: null
      name: application-quality-auth-client
      namespace: application-quality
