apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: stac
  namespace: data-access
spec:
  http:
  - name: docs-redirect
    backends:
    - serviceName: doc-server-eoapi
      servicePort: 80
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /docs
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /docs/
  - name: docs-route
    backends:
    - serviceName: doc-server-eoapi
      servicePort: 80
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /docs/
      - /docs/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/docs)($|/.*)
        - $2
      enable: true
  - name: browser-redirect
    backends:
    - serviceName: browser-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /browser
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /browser/
  - name: browser-route
    backends:
    - serviceName: browser-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /browser/
      - /browser/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/browser)($|/.*)
        - $2
      enable: true
  - name: vector-redirect
    backends:
    - serviceName: vector-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /vector
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /vector/
  - name: vector-route
    backends:
    - serviceName: vector-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /vector/
      - /vector/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/vector)($|/.*)
        - $2
      enable: true
  - name: raster-redirect
    backends:
    - serviceName: raster-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /raster
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /raster/
  - name: raster-route
    backends:
    - serviceName: raster-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /raster/
      - /raster/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/raster)($|/.*)
        - $2
      enable: true
  - name: stac-redirect
    backends:
    - serviceName: stac-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      methods:
      - GET
      paths:
      - /stac
    plugins:
    - name: redirect
      enable: true
      config:
        uri: /stac/
  - name: stac-open-route
    backends:
    - serviceName: stac-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      methods:
      - GET
      paths:
      - /stac/
      - /stac/collections
      - /stac/collections/*
      #- /stac/collections/public*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
      enable: true
  - name: stac-open-search-route
    backends:
    - serviceName: stac-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      methods:
      - POST
      paths:
      - /stac/search
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
      enable: true
  - name: stac-protected-route
    backends:
    - serviceName: stac-eoapi
      servicePort: 8080
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /stac/*
    plugins:
    - name: proxy-rewrite
      config:
        regex_uri:
        - ^(/stac)($|/.*)
        - $2
      enable: true
    - name: openid-connect
      enable: true
      config:
        discovery: "https://iam-auth.test.terrabyte.lrz.de/realms/eoepca/.well-known/openid-configuration"
        use_jwks: true
        bearer_only: false # as we want to redirect to login screen (default: false)
        set_access_token_header: true # required for subsequent OPA check (default: true)
        access_token_in_authorization_header: true # required for subsequent OPA check (default: false)
        set_id_token_header: false # not needed (default: true)
        set_userinfo_header: false # not needed (default: true)
        client_id: eoapi
        client_secret: ""
    - name: opa
      enable: true
      config:
        host: http://iam-opal-opal-client:8181
        policy: eoepca/dataaccess/eoapi
  - name: stac-manager-route
    websocket: true
    backends:
    - serviceName: stac-manager
      servicePort: 80
    match:
      hosts:
      - eoapi.apx.develop.eoepca.org
      paths:
      - /
      - /*