ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: datacube-access.develop.eoepca.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
      - datacube-access.develop.eoepca.org
    secretName: datacube-access-tls
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
config:
  dataBackend: https://eoapi.develop.eoepca.org/stac
