apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: workspace
data:
  domain: develop.eoepca.org
  separator: "."
  storage:
    provider: Minio
    endpoint: https://minio.develop.eoepca.org
    region: eoepca-demo
  iam:
    discovery: https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration
  opa: 
    host: http://iam-opa.iam:8181
    policy: eoepca/workspace/wsui
  vcluster:
    separator: ".ngx."  
    prefix: ""
  storageClassName: managed-nfs-storage
  workspace:
    storageClassName: managed-nfs-storage
    storageSize: 10Gi
    pvcs: # obsolete
    - "rclone"
    auth:
      mapper: "reader-share"