
resources:
  - app-workspace-api.yaml
  #- app-workspace-setup-examples.yaml
  - app-workspace-setup-prerequisites-init.yaml
  - app-workspace-setup-prerequisites-main.yaml
  - app-workspace-setup-storage-init.yaml
  - app-workspace-setup-storage-main.yaml
  - app-workspace-setup-workspace-init.yaml
  - app-workspace-setup-workspace-main.yaml
  - environment.yaml
  - route-workspace-api.yaml
  - ss-harbor.yaml
  - ss-workspace-api-client.yaml
  - ss-workspace-api.yaml 
