---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor
  namespace: workspace
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgB/Hc+8ojZSuaDbiQumkcZQ0tp3NR5AjnS26HPNlZa4Wk/IdqfoqhRG5oZZOrpjkyIfcmT+MWZKFeGu4pyBewjyX62PP54pY8Mkta0VdNyFUVhowrY7x9DmSQYaqChcOlpf+SbszYeb6QAqyVVmYfcoemwuEc2Kjfp+zYOdR5a4urqgpNgn+sLDNT6Ye+wFitqdJg4gLwf8d16IXzerTKS7lFmWd3+HH8C62y3oewMsojtnWbQZILilylQvoMewOicRyEaBGthmL/2FyyAaYJ8KGGpKlea93S+NYVmhsx6/BmSXaJfjfODd3dwReX2XdoD8MIfYTn9QqPVJ9UfcKNCOr5Q+So/mdtCKa/wBXwVXamVhIWJ+LfnpOVp7cv5ElbByUC5bToQGyL9MZy5XJ69RveDzLx96EE1vJAbcmSkj8fzMYp/xDYub10ekd7H4WHHrTBHECLhxoon6Pp+FBrwiHZjwETyf3IbXJ8gtObgk0GfVPGkcvSV4EO2G6BVmnVnPxiUi/Yv3hdZ1I4lpKXF1xofmwPlEEmk/pq75HyIjV3BYhbLP4ZqzGEzMHbz4N8gS68UH4lKfuwfTodDQ7bGeYNmxP/LY8+df9OXW7DxLNDi0u3Oot/DIFK4nfc244EFGch5/IRdPLARA/OL0DfF15+XErHujkT023OXrqxvvljHpRdqXd51nsoKAD0JW6KzKBa0fLPpW3A==
  template:
    metadata:
      creationTimestamp: null
      name: harbor
      namespace: workspace
