---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api-client
  namespace: workspace
spec:
  encryptedData:
    client_id: AgDIOtegAwFoCqRINhqPuUXS6SDzU64e6rkXys1n3CQHKhQdcvtER8hIhWxRn1RkJ7NqUMhi3K55+AnnDTOA4zdwSRveX/odjDMILvzmAvfopwPCdvEk8DUgzKDo+sZlAhc3VtDL/9OfOIcoAG1WzPThs6i0zfkvzeHcNtBm1UO3iV46Ylmh761fYlulvApBsZREixWjli0VuziBNZRCcrfukTgs6ZbA6rtVutQSuHrdvxvrPjJoGojq3avjQlls2ZLdE+N3kiFvD7kzEIdu4JH8QL0NTYGgf8YcR3jlvVDlove4ktyP/gzVvDUPruosgF1VW0DJMFyb34hkGuAVsZeCJj9qelTGhCkcTKiYn570969DNy262M1iduEH9WxGYEaQaS0nbvtEEliGwNlubOttAEyS4IxPaUIa+D2kLZEMYLpODQiTDbAXwNIWVY8SVRE/+lnlerwlPOlQaWezPQgCBXjBUSpbUPiSEoLZmr1xrJsqP166Ob6OKUDa8f4tPM785qw8v3kokVnJ1x0NyrEgd4fjSmBRzOsFJ6OeOV41XOQI7IBMfELenI74AEgzCvYarxH7Y60M368+ys6iC5fpt/0UPqm/Ifa+900cIv7GPxVegE8gwhGXM6TZb96Qu0XlbM4IauL9LJDgYHdb8izMncvzi5xjLHqzKOByiE+D9N4frLYfWG4N81JC/vctIL38jzlj5lD5MCaXzNM=
    client_secret: AgBBrco3E7V8PujimCUWXcACFfm7nS+urHqKJPtYNYlyb5fbYfbWuQMCfsb5X5zPEqdchZPSXfMlQ7QXH3IcBf9tbMqyGfkz/nsfcelUDH39g4dIzsPNzOccy/0kw8o0hpOwRdeMbHme5uURw4Cex0ZGBfABCf0MvudcksT8lBmNej7eHnBkxyA1SaaM8j47UkIvW/ZOqvIsBbO+rkh5AuBkT1+BupFdBTslBD4n95jVmlDG3x+pOBVmqJT0aS2Pn8dQAQYOVN5/nBEwUHDy4BIOuQNfRRdHKeA0kFgbmijekzLzp3iLy6X4wLdt+1B8P6XS6JaekoLvK6oXghsVYN0kd6r5vcOG/45b4ro672ctzO1v0WvCEjvHR/1ipmeePsmSI8Jb5vUkdOGxbJPXX5vYw8CcJFAakj0XkLSQQzgmFQuew+cKikHXuaIyLz6VloOqhaS1zc7YzNyKPq7FTSS0hwe2s6UlOZlnTloLH8aPnmplnsJiNx+UUD9ljr65wJcQkScXt02+M2rpTCniGT1JrJ7GbgkJN6HIkdhA4MYKHNGJZgZjIYdatYnTtFklwv5LNIx7RPC7b8fnOxMTbWOvzOhAljJboFbkDTyVa5J16KYV+08UqaCWCZZWd7u77mHdxZMmTMKlccKrQVkguP/ZlsPVPBlB0/g9hQV8NwygQYqtfMLrX5tyoAl2/wJzs1UaEooYR0Zcvw==
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api-client
      namespace: workspace
