---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api-client
  namespace: workspace
spec:
  encryptedData:
    client_id: AgBrViCOtJYUMlOuVNPgxp6DH13Vw7zM/d0K4POwqpB9XVL2HkJZ5Jr9P1fEiiNKAJbb8qslkyv8tTvH+OIUiCR4sm3H7MFEIL2zEMuKg5nOBNBdVIz0xzVx4gmAuvqgjPgWQPcByIVN1j7yK3Cy+AQpZE61NPxoFEJ53I0+y8g+0BJSSFU/kLBtMPjz1a47M3e3GcD5yH+F9QHt8Y24vzTz7lelHljCSwdwpy81upa6E8A6yBdFr+brhVXnBPEytEiq7xH3AJKaZTgAK69nduV8ZJxsZBCiEdN9szDGLuaySIk5Kt1qDaqnIvxBjJX/YPSCWdnPJBGmfVE40vqfAyFurnpbm+s2HzQGoeOnceaAd9Qzvd76rIrMohmOG/e33zYwdN1+WQWZtFgBuGVMI9EW+eE2MaE3WrH+CJMD2jVXe0m3ukE88urOm7m7y1s1dz+vBdASIN45YYh8HJOVUip2Ua1lqDLPdCK+7fy0varYCzJVR/j1vYvCFDtZYUhNpND1zoe0sRail2RJCJLUqRT4U5xniPP7/BxDE8x5Ht92uzCrgd10KKJzf0Bcm5u3EAJxSxeQ4lW3vmap+UhVAME65w04q++pW3lDQLCdSV+zxTBE3dw9FUPOgLzA5laRzzWj89juEgJUEWPEx2wAe4XKLXsC9hZeCujNYjJJ5uSZDjWeCm8M83yjqtmpiQC2coVSsBK+xRXBRt9gE+Y=
    client_secret: AgC0MOaB9F3yTCRpZ56mnySUtZzyraCPdPuT9BfhcdrxHFloUBL3PXUtOAlrBjAIWB6BM3aofZIgMvP/Hn6uAbqHRfFwn6U6rtTlre44PvvNquEWGRUM9yjnklAoICYbvLQadpHWxwE9z+E3aFbVAsJKIl8nbwdQISCOXw6E5UcKKPQvWx5yR6jPkIQmeAtRZyfSYmgbMDzC5nc4HmVLy58NKkEDd1aJkO4VRkrUIsM7/jcsB88n71D9AJCIv5BrCRdtuZbAEZoqALCaGbMBCr/p3V5xCCuXreCyCYheO+64o/qWstpSJosZHc5bUOZWBoOhN5gsEqrd2s4a532QNvht0XxyAx4yJt08w67rCBxiaLKCLvIMXLmIoHi/q/PlCPgYAkoTWTeSQ+dfy26jiPdEVP7FCuxAa55WJ34dORjNIWkRPX9wpLZkYkOnPqFUJNw/Nf3ySVvNDHJZkTibicVv93IQVHkkApjZBdG3er295GkSByCZQseprAbO2Hb1ZGwto37IdwCBRX77d3VPp+QeqH/H0p0tepkG7InSEH5xdgrd13NJuzNLGpy/wONlgyixtAYUEwwA00k3B49bJa6FJj0Had9EMymUaBXEsEbFppbtidlt7Zv0YXekelLSVrw//dN1lNXO4OICN4Qc+qyuA7oWmaAso0TbtoMaRWYDNmvJsliqEDQzddNKP2jr8refsUmjeCkDAQ==
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api-client
      namespace: workspace
