name: Bug Report
description: Raise a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to raise a bug report
  - type: checkboxes
    id: building-block
    attributes:
      label: Building Block
      description: To which building blocks does this request apply?
      options:
        - label: System
        - label: Resource Discovery
        - label: Data Access
