name: EOEPCA+ Bug Report
description: Raise a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to raise a bug report
  - type: checkboxes
    id: building-block
    attributes:
      label: Building Block
      description: To which building block(s) does this request apply?
      options:
        - label: System
        - label: Resource Discovery
        - label: Resource Registration
        - label: Data Access
        - label: Datacube Access
        - label: Workspace
        - label: Processing
        - label: MLOps
        - label: Resource Health
        - label: Notification & Automation
        - label: Data Gateway
        - label: Federated Orchestrator
        - label: Identity & Access Management
        - label: Application Hub
        - label: Application Quality
  - type: textarea
    id: details
    attributes:
      label: Bug details
      description: Provide full details of the bug
      placeholder:  Please prpvide as much information as possible
    validations:
      required: true
