name: EOEPCA+ Bug Report
description: Raise a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to raise a bug report
  - type: dropdown
    id: building-block
    attributes:
      label: Building Block
      description: To which building block(s) does this request apply? (multi selection supported)
      multiple: true
      options:
        - n/a
        - System
        - Resource Discovery
        - Resource Registration
        - Data Access
        - Datacube Access
        - Workspace
        - Processing
        - MLOps
        - Resource Health
        - Notification & Automation
        - Data Gateway
        - Federated Orchestrator
        - Identity & Access Management
        - Application Hub
        - Application Quality
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Bug details
      description: Provide full details of the bug
      placeholder:  Please provide as much information as possible
    validations:
      required: true
