---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openeo-geotrellis-data-bucket-credentials
  namespace: openeo-geotrellis
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgBWp7gEfUseAXworZVGsEKsnBoLB6owSLGFIrkMzmjBTR895gvj16gcbfvgH5Jp90TLryJSwLC6O+V0X7htbek8GGMCkgC8rFi53nB6mI+Lnztukj7C+QW9wAYQOSqiQKSwlumMlmhxtHyPyaeIj4dNrbkZgusF30NjGRW3DHQK9H04uu9vsLKT0fqWTR5TNzBV0jw6cH22Q1TM8L9cGeV7aCgCbs4018vzTy+Ke9pxPxrZKfkTFMu2VzEvhUEdGgAn8bwfk6ZhmKcNV93TLgvW2eKw94/HzEaR+kehl7S1yk5zB0ApF8a17SrMITU9sYQ3lYVUxhy11e7DY2m7dTmAD2AxSzV38kAlmu/VC0y2eYeNyPfLdCPj9p8w7v9/lFOIEKNAwARFHIsnHPk+yZsHQTINzUYCWMzw5/mKsEljDuVoBniE+02ivPs6jaI1TrREQ7lyhfmoGmWEskE8s15OIM4fmJ+EFMrVCVNjOHlosPYFQ7DhNLKNhGWE4SIoU22DXoz4Ab0DrPcVCWbt4EnpZqoVnn0NIpjg1hqfKGCiAPSC4bL/f+wcWR0jNgPBZeLgjG00L4fCoXD47chrYYqAeBVrE24YJHcf8m+W9oUSJrheV9d9VmPC2/DGYNRwBHRTIgLv6BDsg0jzKeeGUUUsNFBtkMcTTVOjWrFMLK6NQEbkucZNHrfesp8BgrpdL9CILKKr4QtswnJ/0fRJLR00xripCLPrqRoCVZ5NrhHtNqsIE6AskHZD
  template:
    metadata:
      creationTimestamp: null
      name: openeo-geotrellis-data-bucket-credentials
      namespace: openeo-geotrellis
