---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openeo-geotrellis-data-bucket-credentials
  namespace: openeo-geotrellis
spec:
  encryptedData:
    SWIFT_SECRET_ACCESS_KEY: AgB86ZRIRpWBHR12Fq6UXt1Y66gUghkp15sawgC0/KuYwN1NxlA/MZaEy7ZhO2wc5SFTssj6+p7hjEgH55LBi42XjFIfp5p6DuxG6oYG0eWQ5y/67tOxZ//p/qsC6QOGvusm5F6RyE464EwXF/EsCJiLbfRCAdC6vKGRPZ0FCzYeqLwJ35Znjzk9Mf2e9iR/YRIFVPCWys10niWCWRqStevF8Fhf1SGTQ3cKchxFl2KVV47PaJOIRTz1fbwk4Xv/4UbbXwzS00jE7/QhR6geb6nbWTs2B2CHlDwriMP+5GpVDyyNSQLgXRKEoe5FiHwRq2Msn0Va0cBfIjFayNMt0/IKjiqxhEc3/jMDCVjwxW9KG0RWgjcfnIGeYZ8bOWdzpUUOO8tZs03TTo2V9if2Md9dkQIXyvPUXuEQJuRfNoic+v9ToL/cLqJa5eB1IVr2OkF6u0elLZFQAzAAKP/LR0dfJPh5bIIya+38wU+eYMl8c8KqW69acLrNLzn3wTHO+212nSSSz60UdLA2H0cyolxOGHHuYxte07zrPCZ/XOGel0mZYMiNKX0MWsyKkg3DlrHTUnefrlWH6LzC1vb3sjnRHI/KDdTof4IVnjj49XYYzItnn8gtlwYbHSl9dKKPFsqWwpGfEgpM82VXDFOuKQZyS7YI1gRo2E+HFWMNOjIaXpAf4Wc3IALaa4/j/rDopvq6UdlVw9RG/4SKXL+uzLHPDF6vUUiDopjA9vfaIJV1AfswO+dUuuwP
  template:
    metadata:
      creationTimestamp: null
      name: openeo-geotrellis-data-bucket-credentials
      namespace: openeo-geotrellis
