---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openeo-geotrellis-eodata-credentials
  namespace: openeo-geotrellis
spec:
  encryptedData:
    EODATA_SECRET_ACCESS_KEY: AgAmjICSr0pAh8fmNaC8y5fpT3Ks1inaruPyWYDQYEfZh7l2wMr9cloC1jdCvDDAJdrwznrp3hJlMlS4G2faCWx7pru3TkfesYwypghpD9RA2FxlaPLuHqNFAeqrjCFFZrjPsdJiFfPht+Pjh8qZv3seYgXLOBBggveo41sevw/h+QA+ggAelWKg7IrizrqRsng8c0tIoqOLg/RVS24flGWyQpi0gCjOCLz8jn5CfhzwOG1sXKkyJq8tAscSlwkuMMb0wNLewMEM3tP3K+xRVevxcpeNO/X0Wx4Fepd5bdwlbRet8TkrkxXX19qAUT2pWbMPZgfXNf2SPYdCB6x9LIgzLNF9uLyU5g5InrxfQRA2xFW6dayQ3va9tJYtzviWJsONvY/tB8SRPSK2IUaL6o3ghn7nVvdsA6zpwwbGyxExa94xiUX2aUTo8i0a6WO0bMqYnk9wH6CYiIr2edIy/PLDDKNtGgtF3PHIfrWmttPtNzSQ0R1269OVy6E5gzqYy21dVqymLAtLFymscOhRm7xyInN6EfPwuKMMzMGWoB8tXi1k8GOfT5UnZETGxIvzAGY9dDPr9P210wkVqDaOxZ1vXiTDMQ7+OPQIDQqU0kVpqgQo6wZ2tRMetrvbNWy2DqqBotzdguvLg6nLJbJKeVPyqY3puZTWopYir2+9gWjXgUFUFV8tp0tOrEffAzhq2hXOMwUkpZERGZPifXR3h2p3r7CklNzYCQD3StQN0Ebbyo+XotUxvQto
  template:
    metadata:
      creationTimestamp: null
      name: openeo-geotrellis-eodata-credentials
      namespace: openeo-geotrellis
