---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openeo-geotrellis-eodata-credentials
  namespace: openeo-geotrellis
spec:
  encryptedData:
    EODATA_SECRET_ACCESS_KEY: AgCzwzNgdLhtjmRrltvuHxvOeifKw+A8CMlKH9uN/PU9dfDCPuCSvYz8N7R59EbTFQf9arIkH13gkd0zfkX9Lf5Gzp444oWdoR+BjOrq0iLCDueVTNW5zWYOwJ8fuUTYCR9Oi93KHlg/SEeqKLUfsQLlE1rYya/TCg59y/DyeSS3AzxjvniUWGHFq57FvBVH5RhaD/z9sO/KuEBVqNXtW3duobTwsp3hA6MAojc5+U3MjW4PcfQLFJ7Eet2bqPnrBD/Zil0KjtZZghgDnxxs6seHQXTs6TD6AFbt1KhAycyLfCwcFrIVTS6pVEfj1flrQncU6obkiWyoSaeEzzfBDdQpyj5RMNehVn6lv/EnKU7Tz54z5vwLIii4BVaI33dYJEXZfUlJToawqUhYtGKk526TnV3qazFumckBKgVB9W3Xk/njG8kfiTdHs1AFdMAMH+1hv9bQT2w60ngn90pmxoXHZ5Sp2RmskuYvEKjZdq6LQ6pl/uMgV9QjD0apVn+U6nrEJh4VYMieCUTZBgMspYPTj2FEgkhc4dmC21DrCrqBa41fC1zMS9Eq5rFjeYXhIOZpg8HGByt6ITu9XdOnGLxBQqJksyVxVPcZ34T2Of6WKg3pvQC7EZzDfaUDBcVAfJ7EgCgafQ1anHRwFt8XkeAW9pN9cZMtqwojysKPviYK5bWFHWb1PspnlMhjPMSPp19LqetcQ/zFOCjzf0lNTqJbpzNKhKpjfWK9aciR6a6HhLF8Y6NWe6Jd
  template:
    metadata:
      creationTimestamp: null
      name: openeo-geotrellis-eodata-credentials
      namespace: openeo-geotrellis
