---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: openeo-route
  namespace: openeo
spec:
  http:
    # Open access to OpenEO API documentation and discovery endpoints
    - name: openeo-docs
      match:
        hosts:
          - openeo-eurac.develop.eoepca.org
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
            op: RegexMatch
            value: "^/(openeo/1\\.1\\.0/?$|openeo/1\\.1\\.0/\\.well-known.*|openeo/1\\.1\\.0/credentials.*|openeo/1\\.1\\.0/file_formats.*|openeo/1\\.1\\.0/service_types.*|openeo/1\\.1\\.0/udf_runtimes.*|openeo/1\\.1\\.0/collections.*|openeo/1\\.1\\.0/processes.*|openeo/1\\.1\\.0/conformance.*)"
      backends:
        - serviceName: openeo-openeo-argo
          servicePort: 8000
      plugins:
        # Allow CORS access
        - name: cors
          enable: true
    # Authorized access to OpenEO API (job submission, user workspaces, etc.)
    - name: openeo-protected
      match:
        hosts:
          - openeo-eurac.develop.eoepca.org
        paths:
          - /*
      backends:
        - serviceName: openeo-openeo-argo
          servicePort: 8000
      plugins:
        # Authn - expect JWT in `Authorization: Bearer` header
        - name: openid-connect
          enable: true
          config:
            client_id: "openEO"
            client_secret: "8f7f2fb0-4347-44be-b5be-d752cbd3de11"
            discovery: "https://edp-portal.eurac.edu/auth/realms/edp/.well-known/openid-configuration"
            realm: edp
            redirect_uri: "https://openeo-eurac.develop.eoepca.org/apisix/redirect"
            session_secret: "d00875a6796744fdb597bd39fb0f4473eurac"
            use_jwks: true
            bearer_only: false
            set_access_token_header: true
            access_token_in_authorization_header: true
            unauth_action: "auth"
            timeout: 10
        # Allow CORS access
        - name: cors
          enable: true
        # Increase timeout for long-running operations
        - name: proxy-rewrite
          enable: true
          config:
            headers:
              set:
                X-Request-Id: "$request_id"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openeo-tls
  namespace: openeo
spec:
  dnsNames:
    - openeo-eurac.develop.eoepca.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: openeo-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: openeo
  namespace: openeo
spec:
  hosts:
    - openeo-eurac.develop.eoepca.org
  secret:
    name: openeo-tls
    namespace: openeo
