apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openeo

resources:
  - helm-openeo-argoworkflows.yaml
  - ingress-openeo.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: openeo-openeo-argo