# Copied from identity-service and adapted

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-keycloak
  namespace: argocd
  labels:
    eoepca/app-name: iam-keycloak
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
#    - repoURL: https://charts.bitnami.com/bitnami
##    - repoURL: oci://registry-1.docker.io/bitnamicharts/
#    #https://eoepca.github.io/helm-charts
#      chart: keycloak
#      targetRevision: 21.4.4
#      helm:
#        valueFiles:
#          - $values/argocd/eoepca/iam/parts/values/keycloak-values.yaml
    - repoURL: https://eoepca.github.io/helm-charts-dev
      chart: iam-bb
      targetRevision: 2.0.0-beta2
      helm:
        #releaseName: iam-keycloak
        valueFiles:
          - $values/argocd/eoepca/iam/parts/values/iam-values.yaml
        # For now, all services are disabled by default in iam-values.yaml in order to
        # allow installing them as separate ArgoCD Applications.
        # This explicitly enables Keycloak.
        valuesObject:
          iam:
            keycloak:
              enabled: true
          keycloak:
            enabled: true
    - repoURL: https://github.com/EOEPCA/eoepca-plus
      targetRevision: deploy-develop
      ref: values

  destination:
    name: in-cluster
    namespace: iam
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
