---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: identity-api
  namespace: iam
spec:
  encryptedData:
    ADMIN_PASSWORD: AgA1K8WRNNsPg8wlBIKcbYLbaQSVL4wxWv1WNJNDIdbIfJNl7d0iqMBnxk7uzP/qZcfDr4f0HekoDOdrDizwcM5UKKImc0law1/WzOiThaohtVqEEkP66EXjGNEYzi0F6mgMN+ceem+MhgS7HcUoJ6qdNP5SqlpGqH6qOZFfG3isxvHc29WRp3yvTu1Qw4GOb/zgP2dR0Epwtj4X3fm7Ep2KwIhoF9LQjrP1fntuinusDZepjIv9OaRFLp6/LQAJH5cZh/j6wX1558WzSWSt7G0FRw0xYArlCAoO6es2v8vC8Uvxht2D+kD16a7IpvuHt/TcGO/eC3wfnwr+DddgJRBhFsyEEWINJznJz9LjWTS7RyG4HL4b+ddUExK/XCTRd8B8M9M58QciqnBkIC+Cj4mJaK67enG+zcQ5xkFL0H3EQMvpFoWZ33i4Rp4WdIX1pOKUJ/kzNBrZAHw8h5zAYgE+Ox2YUfJxSfjUXvHyLVDffL1NFkXV779EIQ6DyKNY3CV0IKe6ySH9TNePPW9qWPi0glKjnFpD5gEgqPYWjSFyShjaWEYXpWOxnLPlqe+vYx1Ffc2ie8vtBnBgb/v0XzvcW39iRKejJc1Jhuc4xewyLY9/runbLJ3PhVCsaqLGnmU9/5/gn+bLkZ5Q4+rZUGLycHI2Ur+0NaafnbPxL9tJKrYhSatAQDFxNQ+fKY05Oh5GEs94jgk/cDhiWQk5
  template:
    metadata:
      creationTimestamp: null
      name: identity-api
      namespace: iam
