apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-setup-common-init
  namespace: argocd
  labels:
    eoepca/app-name: workspace
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  # Ref. https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
  project: eoepca
  sources:
    - repoURL: https://github.com/EOEPCA/workspace
      targetRevision: v2025.06.05
      path: setup/common/init 
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: false # never prune
      selfHeal: false # only manual sync
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true