apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-dependencies-csi-rclone
  namespace: argocd
  labels:
    eoepca/app-name: workspace-dependencies
spec:
  project: eoepca
  source:
    repoURL: oci://ghcr.io/eoepca/workspace
    chart: dependencies-csi-rclone
    targetRevision: 2.0.0-rc.1
    helm:
      releaseName: workspace-dependencies-csi-rclone
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
