apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-dependencies
  namespace: argocd
  labels:
    eoepca/app-name: workspace-dependencies
spec:
  project: eoepca
  sources:
  - repoURL: ghcr.io/eoepca/workspace
    chart: dependencies-csi-rclone
    targetRevision: 2.0.0-rc.2
    values: |
      NAMESPACE: workspace
  - repoURL: ghcr.io/eoepca/workspace
    chart: dependencies-educates
    targetRevision: 2.0.0-rc.2
    values: |
      NAMESPACE: workspace
      CLUSTER_INGRESS_DOMAIN: ngx.develop.eoepca.org
      CLUSTER_INGRESS_CLASS: nginx
      TLS_CERTIFICATE_REF_NAME: workspace-tls
      TLS_CERTIFICATE_REF_NAMESPACE: workspace
  destination:
    name: in-cluster
    namespace: workspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
