apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: storage-minio
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: ghcr.io/versioneer-tech/provider-storage/minio:0.1.0
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: datalab-educates
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: ghcr.io/versioneer-tech/provider-datalab/educates:0.1.0-rc.1
  skipDependencyResolution: true