---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: workspace-api
  namespace: workspace
spec:
  http:
    - name: workspace-api-no-auth
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - "/metrics*"
          - "/probe*"
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins: []
    - name: workspace-api-docs
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
            op: RegexMatch
            value: "^/(docs(/.*|$)|openapi.json$)"
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins:
        - name: openid-connect
          enable: true
          config:
            access_token_in_authorization_header: true
            discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
          secretRef: workspace-api-client
    - name: workspace-api
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - /*
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins:
        # - name: openid-connect
        #   enable: true
        #   config:
        #     access_token_in_authorization_header: true
        #     discovery: https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration
        #   secretRef: workspace-api-client
        - name: opa
          enable: true
          config:
            host: http://iam-opal-opal-client:8181
            policy: eoepca/workspace/wsapi