---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: workspace-api
spec:
  http:
    - name: workspace-api-no-auth
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - "/metrics*"
          - "/probe*"
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins: []    
    - name: workspace-api-docs
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
            op: RegexMatch
            value: "^/(docs(/.*|$)|openapi.json$)"
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
#            client_id: "workspace-bb"
#            client_secret: "nbUmFfzQdfcYiLw0Mo5OMzSaKQfZBv3U"
            access_token_in_authorization_header: true
            discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
          secretRef: workspace-api-client
    - name: workspace-api
      match:
        hosts:
          - workspace-api.apx.develop.eoepca.org
        paths:
          - /*
      backends:
        - serviceName: workspace-api
          servicePort: 8080
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: authz-keycloak
          enable: true
          config:
#            client_id: "workspace-bb"
#            client_secret: "nbUmFfzQdfcYiLw0Mo5OMzSaKQfZBv3U"
            discovery: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
            lazy_load_paths: true
            ssl_verify: false
          secretRef: workspace-api-client
