
resources:
  - app-workspace-admin.yaml
  - app-workspace-api.yaml
  - route.yaml
  - ss-workspace-api.yaml
  - configurations.yaml
  - environment.yaml
  - oci://ghcr.io/versioneer-tech/bases:csi-rclone-f2d955940e1e