---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api-client
  namespace: workspace
spec:
  encryptedData:
    client_id: AgBp6dKQiuEutjd1adIO4PHucvUVJStZQYsUp5vR+oK/0OJhGPAeJcfWvAmqpYLKv3cwzMJFveaHbARi3NzF3gYxj42rKYS7Eqzf249uhn/Juo1RdjZrWNd8zErg/8Jw/n7LaHD6nCFky5qMYwS9musEYS6zIm5azv24u4Eru3F4fGd0ITnHYgKXap/J8OcfVD0AuVXlhJtQjzrIXCHGvLlb2uL6KgTtHmPhIAJgNu6j7qLUChrx4paeTP7l1dB4v5R8hdHsHbxDNFJSjSe64nXFE3jeIvX0LWDOajUacnrz8kXY8YB4kzAOE4RO97WzYZwNkn1PH4KixzDF/DQY9M4PaUq1aE7ftHMBI4d6/CFW515lrENarOpo4LjPHxzWkl4el3YYA6wUxfKM10QHbhNLMcfBRv5Mb261u7YjMCh4dqiWROj6ffpjelnXtp1GjrVW52tNcs0xzdCMjtYGWVWip5afAk4Ge0ZyKPLHSAvIsC5YeuFu84cQbRIzNihygHUx93GkRxAATVaaI9HPi8sj7a42VmT797zC/pAEX5tQiZbcJwPU1zRwTqOUI6tMGYLzKy3REHuzJ4i8oabrpO7w9V4t/AdSUPQZa3+gs5JGQkDg4oZTQdYYq3fYEm8138FTumpQqaMG20oM1T0QtseBMqG6apRTG6xd8Vb35ng3CAsydXCcGVgRRU1oZuj11ULVWo9/3FwMhVyWVfo=
    client_secret: AgC3XAOArc1HXaZRhUAtlaHncyvm8pbWXGnBtL7PwPzsqzYkcvVmlzMQQ3ANAL3WsllVnf+vp1KUiDbCgzFpct4iKl0vqcob9sRjRlC/GD6CJN5ZeYPzn7uCZiYe0BC8z4+KWzinjxJ2QD/LWN2Dc3LEzwIbGJpAcxcbaqBDiS+Wtd0zqw3eTjHKAWGQheMOQBqyyRxc0K5ME1+EQXnCG4pVexVB+s0lzsY5c+jgMfxDGJ0FF24eb4aJStNaJ/DtUtL5QzYcymZ/OVIjw5G7imzWsv/BmomXzcSetjNBowH1T2HW85PxoW719ExHMyxibsCkgVuj/Iz9ZRd9K9FY9puHFmLOda6XAgNPO4eAyoi10eOQeFutiZx/uKlrwZjIyiYigA+hYzj+X5Yvo5xdHo/GjcMZKB5LNPQPZlIqVNrdZsSxZf7/lo7Q1IY/TmX8JtywwRdhsUcn4gwdsgv1TkbcCiJ0pvVsTdQKQfWOHrfvHCvAKFd8G+s9tekQZGAaoW5PtjUE5JXAq4gvMePcukX74LTczpV82bJKx23HozugF4Ft93dada5ftlGZ2u5jMjOWpn+Qb3hZDbmXX8JKXtoY4v5swVRI91mEey+c6hQ98ZgGUrMgW9MNFsr3ynLGtI0G7rqcxpC66hGOL5NJOKnNURWvBKhrysZErVaFJnwHNbXIuVRsBDHfKtwBsAyRYT7IR8Y2CJB4whR6Nsrh8HqxODvVPm+NEOnuSfvDlRwWhA==
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api-client
      namespace: workspace
