---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api-client
  namespace: workspace
spec:
  encryptedData:
    client_id: AgBGviZkary3TVvfDebqeEZbbty6Ygop2AwWRq7Q2VYxoZg/if8XDA0wvk2ukTFGfM11Bcc60PD3tJxOsaaoLEx2azMab2W774k26pIZ54qtQVpBuE8vcKcfbYNUkHRQ4k7bU2MfLy9mHlcRe+ZY46tVf0c1D5sMCW0eAJIDH7JbyipLQEpn2U1TpChrNveRlK6xOp7LN9Njo4T9xxoQezmDbNzMAGHlmFlePXVoBQ3GuKHMaogRgOSM7EMPmPS3LxAE1wRZLKO9O4c0KTn2vGtfdht1+mtZ1u8JO4kjzwvMRjz39RESvxdalDPhxf6P96lqCgpSi7u85Pj1cPU6dWRtnIWbicaysLZIGmxe86zIQEFCLcvDClDGSCb8ROicxBjVuLiaVJBOUg/l1qMe537juAlrY7aoTEKOXVcqqHDjPbFgyvoGsOB06kONkD/wooQCfa9ZtjZWEgG1s1Ug3PYVbaAnwtJXS0pzYlxX3nKCBTJlOg26p0G2ITBGl9oinUML89ubhBs6pz6OzT6H9dJhD25/3E+W2QBEw9u02QiXH37wj17Xd8C6A5rboJeiSqjhCqyLaeHXl5kByZwzT8gDNGPcxcrxBkbqyj1dzfY5PociE8EOdlr72HMt/cX4sNVkdTS4BTmKTGIr48OLoAj/4LapfyuWzctYojBF88qmXN7xjM6sZyQdI5pr+d6ohGTGg6t2rWPp9tf8Q6A=
    client_secret: AgB6ganTIl144sFwLn+Jjk+xu5rYOBeKoQkFac5oZAfBTmeGhrydJoUpUOVLH3k3JKEYDp7T1v1SBv1agQlhVyztJzzqffcdti/lH+ynHRiX/X7pyjr33nnkJVQC8xnT7n+j51oUuW+2NgZYlJU9dr+QPxGAnzaJQE75Z4k5/PZDjHEwlgc1AehWM+iUg1stc9JlTvFA8QfaQk5qnx49ZUobzDN1ys6vP/4LyGLLDDoor8oGQh4pX7UCXnpG+hRse/JUQ1LpGSmFTmqLa+t1N4KXCFPAW2KB2j31MaUsZjL0pcwB8TIcAEQpnmialtnHaP3r019NYgSaYtxqTvuik0tYMtZAX+w1DnJ62VYvdcScoeo/ab5OprZqpjP+NnSf+p329lj/bNcMLih8rgMxAwpsUhC6POuMlZjcJR+IB43ChjPpj6jX5mcS6DF6assiohMKyIhkNifDAmRVbpaOAAFZ2MMBzPmkhDWS4fXmvD5aoXy1qaUOS+u+UVCnX5mgNy2EwjKeIGJLBcd7tfFWGFK0PNte56OYg+ayG647O8Ccktb/yOovRK/Ut4yvC7Q78bF8B3FOL+zv7jxm7bI8bOQQyFB+1CkCLdruvFB5lH9I4944o3ryscO3wT7sLcwH91cyC/aOwHZCWmn1tk6nLyeYTsfilmMu2VgWTnABXuiF/WGZKXaD1GQJG1ZhBjQE6YFjj79uS2/Ptq497D00eva/xmAbiqiaVtR1wDxQXf9xOg==
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api-client
      namespace: workspace
