apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api
  namespace: workspace
spec:
  encryptedData:
    client_id: AgANScwu8XYnjc45ud0l4vx3EWBwQrB/Q/kyVoYe/WQ2Ez3MKgT8CRfgTVPaO0DRDkoJkextxYnYbKJmhEPFcsCj6Ae2wzmi/bqZMiqWNPAVUMiBzME47lsWEAySkII/0ISZjG2rkoaKySshFLf3Ude9CEfHVivhIfHiBuHoHDWBTXoJwBkMbDA5cYmFKCYZ8oZ60Jr3OK+jLtzcj8wQwO69Rj41ziDWk40gdR8u0VahbD59rOPoAbeMCuYgTSH2SgFxBtl3BOaTWIN2IMaoffoH/XC2arXxrldsL4CXmg+G0Hzzhk/2WdmQr5DHGvRgSSeoo/y8wwTPpViOm+ZAPQ/5Y8ZyP4RehpoReOoim2yLA9OWq+z8Z7Zy1heQaENH7G3BhgSEMB9P5NbfqnixZIK37rIk7hhaTvVJl1ZiVTXsaYiElzmuekHnfH9jdpKsaG56Lwk4K0HsCF/GxzujM40dH4TCpsvzrUPm3CHzB6IrzeR2puUj8X2e+rqD2X/SLZydyvaeRjkJIo3Tb6evecFtBs8iO+KuZF1KUiIIJTHmKAiJW0ghSul8mTEYVAT6QVo+e/+NESvtrmRN3QEMFjwA4AuACAuo+tf6OUi0UB47HSn0iaJG/SDZaCFBd8DewAMOBM2uFPe315HQwqqANZRZSaU7R7meDaN71S6qjAr7O4bKKjfAQ7BKCHJhUVIuPDesyCBwG0uoqAmV5jmS
    client_secret: AgCtnYAnj3UYmbNTYaiQ2fSFKQgCL+5hS14jbEZopEy66eAP3IwRbl0TMQ44FJEQG0nMEiTttqmuEWpqgfBIiEaQRhOkQw8fG9iu3flMliwmC6+Vx2wsQwbXhQZhaDNZHHIaDxDP/iA/JAwfONpD0Halg4TueWY3sclLCBQVyHups941dN+3OHXQxONDGGCVQvClQo3rW/No494kAhFTnylLZURun/IVq7yJJCXshwPjciunv+qCRVGf6o6wog7rqSnenbRZo2UUt+8OTaJnQI4an5rgiBYK5K17tVOkR1hnrarb5NuTctanEoVtAqmb8s2QPxRQ4AFNFiFeC6VkkoX1OxLC0ufYM0vW6UUOL43Mu+SYtGCcKBFi5t2d7NpbwhSul2eclyZmgGPlJ9VZrY9JWH1ddsTuvCQMPkgryEu6NZlb5mf/fTNgvTVUmEYfrX7XGaTE73UomVVD1sTEkOV3kBtVcDoOnEgQ/CbP3JFvHYCMyT6fYA6M9bl6jBOAqc4BWmaqMmzQOZYlf1FhNYPwj9sjVwLs7f2Zx9KeFp/no+r0/TtqPrxEenonjpWRdTbQ7rjQLyqpJzKX1jMVIKyaT/d9s7oG2JLHndqGx4ZIzRPVabMx5KcZUHZBaNOEZGKl/GmECfcf304fg41o6hfcOomh1jXQ3VEx6rADPyKSvNxNqSzDnz4G8pQM3HedxdBZmgjrFYxaW6qBc0Tlrxb4Vjog0orTJQwo4CP0uXJwDg==
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api
      namespace: workspace
    type: Opaque