---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openid-connect
  namespace: gitlab
spec:
  encryptedData:
    provider: AgBdacg89Nml6SxyLO7XTmKigB0x58GtVq3/sxNUfpcFHea6YdBor7eNol4NDpwZwEMfYW5wa9L8PXo6sppY1OMv7bgJsd0JHskXvWpy6sfqrF+AdvLQEXPWASnmKBJ9tVfNeTt8h4m3lwMz7F3oy9y8xsZgMdk7pEe+T+/TOWD+S1YswPvKt8WO55T5yQKVn2ghYLFHuCu713/oQockBmG5rWqCK/jwnTzYoIYsKAEjOM2i1tdGoLtgg+wbcirBl3/G9KNidQDM2rIaxtKcQnK/qzrBOvuyKa+VjIByPmsoPlHZz84jbdbN79yHfUda1xZLDGO11z2wnh66BJsvDs8qd2DiCUfO990grlM95CCe46wcpPGKT83mxDw7xHsVWmm7BUNfqQPUw3feqDO4t5fqUWdzotuQMHlkzL4iHb4O0/lt5T63mpMgRyqRLplrsWLkeErTUj1NHxfGcPQgQLlU69xg2aQt59BorBlJPbAG1NNIgl4csU/Am+bwviOR4WM5FG+zj6UFYZjZL2DeoKfC6uEirc9thIUPVU8rJ8hkCBin+2wNpgLBA72SJ8w4V9qn6DXMVTR4LRxY2MBC02cU/F4p2GpLA/bKsGOatrt9qAyTFFzwm+eXy9HU+vwdOe0hFeyz7ASvqiVcjVZJ0fAq+bkgjaXS06gt+pybg4EAuPQ+hQWGb0D7t1X+lz+agCWwFIrS8OavvoaKlzCrebA8gVIQ/MHLxIwYCc0KvAqL+iUkgDgfgaZbds/GOfTwsQTrAvfqAKXXV2+eXjGYL+z19s9u8+gSrNSfLCYewji2yyVN0qckCF1GXZJElsm7Mu2kM2Fs7ii8WrHMxqqVtufBPicCV1sIKt7MW2NVaHgxFpJEfN/CfA4MSeLz9Z5apflvoSnRK3mlXA6AqFioPTLh3DaYoGdKGlDOOhMsobfkzX3GthSsi3HEAWXh03mFpF37JJ/jGnDoWr49h0JkfRH8kfU/mv8C9wOZQIupS2FhkJFciBSzNvOgtcr5atIlHpflemATTiXTAzLD5YBoAsB1aJ89LiBocFkThnN4wFPI7HAaEFyWMohtvwgre8+Lit+bS+GaM4dCHr0ODqs2YoY/cbqNZcOsaC+qpI8fZHfbf7rvAVe3xOztxDiLUyJQzdvNb8S0JLZdQlLr77bOkYgAqHSadakfDRgTiPyD8TRyn9weFQE3hFmrBF4n5K3aj4kj5kXvfazQ0CzPd18GcK4FT9KLLQn8vF5mJ7PJ53fa9TD+z+Dp8sY8XpX1N1+NUauSDjOynkO2+bixn0IbPAZy/ODVRWc8uQOXwaqE0rqD/DMlJlHn9bLRp7B7apYH/erHPMRsBQT7AJh1rlbJc2uzUhpXycZ6yunPRtkgugJxbrTrT098q/pn6u63ERI=
  template:
    metadata:
      creationTimestamp: null
      name: openid-connect
      namespace: gitlab
