apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openid-connect
  namespace: gitlab
spec:
  encryptedData:
    provider: AgAPmi3WjZ5dE2Be/gEv77krDXABXApSe5+V0d2vpIq+5p54YtZmuPGaWuvBamfirWwfRPodud0dWZZxcsGlSdFqJ7r6QAbz31SF350rqlLioQ1i1Nml9TwjaPrjpDsVnI1rih/6V3UTv7tOajfSBL6kQWvEXHRBXwYQawFmzaQZ9JL2SC+pn7NEbKV30RPW+1WLD/JTVM4IPjmT3WaFXQ8uuAJ3UJ5RpPvlMvyIKrtrn4Rbqpox3MbKi+upPixUQsIQ6L4x6isNrl2clevYpv7a6K/htVMyW5rPUPNRPKMoKWXllsKz9aRlHuLS3+O3J6mbuPFLrYKRMOw821t/qTrRkiiJPA4uxfIryd9nLjQ5n/8UQCt8Gem8+WrNEABADozPunZFyjvnVdbnBsFvvdwpu+LsC4eVloQUAnQaCr41zNjMmQ40kwpjZWDNw9xByRvY8OtvNWoyH004HYgojzFfn2tTq772f73YxZbMv0v3Df6kBn5MRz8688iL8BOIqxM2qPQy9GNYmoWK+u7pqYrfPWQOt8jIQn77syqczXx4BgGUDYRx+cJq06yWxoutcL7yzAgC79sSNNeQu0mocq1p1VazIAnDbfXcOinNTJcyBQUyggSducbDHH0qmbmBUwK2OZ+CZshUjPl2m+SqKXN+Yv/FRaGevuiwoYXWfMX22Fu22nLkANdI8CpQjVpO/i3JKl8x6b1phH3/cPDNfAgO/zmJttIuxpeJWce2lbaELDSkWBcHrgmiba59+1UgD48zSX+kT0P6orNfBTlAqMrFFF7R5wkLaLsFZgurVoshTNeHswlLTCdfk8Yg9rENXiTXkoMypiuNg3DcklARpIM1SMgTmuZjifVIK61rbaWNSPryZ0LXMqnmGUyZ0sxIFCuOWhU1gj9EiDfTwZJ3ll0xNoklvuEHrhmyTdisQGCo7OlE1YhE+SYAVHwx0NHZaHdvBvhedvsGwIhSntDjBG5SQc3WmxiV1tNu0ZPurHuRYYN+ereGwcjCT7bbIjQD2mlv0saH7VoYxoPWPvzbvZkuVeTPGlLWKvt/J+oI0h9Szo7igkdvHkTgvw8bJ2Yt0t7Wdpn3kN3oGCSNqH4AeJ6/J4XlE5OcAAmdkwZyY/fuLMIhp2hUVCiCcJbUKQBMK04zTuaIJ69csLXDgFpX/eXiEjSXk0wA1tg0oArph5CLUO1ZsmjnZejIjhlfjhdP09JAG2uOzTDtxIkX52DYi4Cb+qLgI3EHLpuW2vodixcm6lkmlNX8fCYSK5/MU0B5Ef50NpWtpLDwjHZTSWY4JUd7aX36l7zZ+5W4CB3JIziZY5wJZPLA2qEI5czkIfiGsXdWs5jYgB11rRfA+eyi9q8ZWthcxHIJOQqMysy3kyhy/RanOE+Bg/BmDn003fhZjNXDxQ==
  template:
    metadata:
      creationTimestamp: null
      name: openid-connect
      namespace: gitlab

