---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openid-connect
  namespace: gitlab
spec:
  encryptedData:
    provider: AgCoLb4kKCQkF0ehYYRlEPfw8Y4ULuBkRaoWvMubOdoaNTDIamDzN9YHj0IRjBR/Ds8gffaOndpAFjXuIyYUPHLlEZ8ogukJtlsUlwTjMBT3wZkTCEKZjl+2acoVpORqYGKzpFPAALNc9ZpU0omtoK9txSe+Z9AyP67fSfHPVWgJP+il2rrBXor1yJiw7mqbFzxDum7VI+fyZ+MLv/x8jps015v4eRcVHNBLEGYb6WYOCVJs3ZI+9oDXYqvgwVLe1eB9I0dp4G/Ye6sl5bcTa47yCBw1AMKoYH6GJjR+OTbBJeDby++lKOu2mppYAc2yWTdDqSbdRNXDReiiL2NBIrp0rSHCZZijZ5UvpVMdXGskxUgqC7BVXMidps6SjfjxKitagziw18/ZNgI5bS6gHd3AYCtXVUyigS4QnrLBEVEZkRnQV3rQEpQ1pc1YiMOu2DVryZg6otQbh+R5s06hcEQ4dhb66MALkjGoU+vZjorSzOmYnbkficuyrsXVHzPehgu24X+04TDANNGnuWMb/3BOOBhVf5hsGIK32KWiFzcOcxdu401hS5GP6AAddu4+uw1j1Rg8TrmOCaxOVwEkZEecLxBKBmiifSKfXsfARh9PR19Op3qBeW6ZOwgpdpMrzbk9GX/J45jsqaIvBaRrbp6bEUKl2F0lJ/LMImi/6DyFhTA5GVtSuyTn4eMYDsvckvk7b7/z1S7Y/JhEZ3mken9Z/vSfhOeyaghJFilokPKFti0A8vSSdU15l1vsxpWtQBWb9+BJA2AqSxk7u2rKXtRsvylvR2FVfBJJp7Tjs80lckWm6W5x8ZKPZXX2mI9LSSb1+lYMBnV2z7L6pgwUl/1jsRllRzsGe9XYf5n3zt1q5VO7EOa42FEAw9wOOTKgr8O3zlPIBqagq5W2RXUC1hJEQuz1mueTrmrliQDSi68y3YEWbk74AYcykeSSA5BvZOWPIWdWuGLcOghQYQeiGY8L4xc6we5FsQeLGJjtMNEYknFWSrc6OtiFZGJ3LxKDG2Ja4SRk6OOmI1Rznq521DRGQCGhD2FTrSSosemLjtR2RuNksRXk0MuQUYRXb2TzVhpU6394fHZgeZjW4KrASRZKHJs/dgL5rCJG0P4nn/POFgnI+DMwEct+04RQSHI+ppyq/s3MEmYwQHAeGPd/7ce5ijXAYBXUb2ZVRp60dsTjw563exiIidyWUilAY+zRs7ehY5p95/H/bsPwW28/8BqJb7ekXkMUetKpd3t8xUYAHjoC4WQcrFOU+mYr7M2qv6IFgZjBRpwLYW/H8QLQjxg+ClpTfwkEOLa5aqfMM4rnIknJ4ukv9XNly0wD6hia0ycosOkldbzRyE9ehilqcqWdo46Khnda/Z27BdbkvTmSuFWwxtwF5r0Cf5PZ+vdkPn/9ZJkRRQ==
  template:
    metadata:
      creationTimestamp: null
      name: openid-connect
      namespace: gitlab
