---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registration-api-secret
  namespace: rm
spec:
  encryptedData:
    EOEPCA_REGISTRATION_API_IAM_CLIENT_ID: AgCRiWvTLosJwXcqqiCfKZ0nEdAi6Qr7VwAnXko3zRGJIKbJykOF/crcasjyNOxA3AenwZAYG8BJ3Zn3sRr7XH4XSaqhnAVKZvNwRDUCGGFKSltgSbreJ+9ITd6Kt04Up9ZRZ9TCngAi8FZv1Nd832D/XUYpRZUXTHc425IGeZ9z9Iicyld5OucCatyvjLs1b/RKtW8LKKEM/TO9G4i6X2L2SyT3tpdpHuvzyozaPJ2NjvkXEyTs9LWixOQ4IV/LXAPdNeVKiZhvzXaTsVH0h6EpfWq6nq4J0846ERRJOKsvV/o6+9IYOi5ThPh/2QuwG5LxknTuxVsMPAHzRb02ow9MPSXDjLhjQ5we8Y9CM03koTAipdzrmynu89JMVqrRoMdoM5VcYCnRw2P3CAiFuV5mrzdKkFNUgK95KOfUH6AmuTqR4ps1m3lD2g4AC8gmiKZK161GCcp5oYq6m4guwFJPOZsx8w7j8hxTF/+m7w3SWucAnAnacBxbSwd7GKY6uBqCDFVmpbWuAqaieaqnk6Qde+h3RMY5YGR/2if7+RfW5EvbwT9lj6lU3rRqtzF8OgCmOKoQKwyWy2JVkvSsn+SY5V01MiGshFWR0Zp1kpyjudmE/n9Dgxd8UsMlzUae0W/9x4817yw4WDmdRAppbvxnFcFDeonc/El2pBzvMoBtGlNuiNmXz0o3hPusb9YOTE10a8AKIV7xjXcQ/ej40RVhTEez2T1L
    EOEPCA_REGISTRATION_API_IAM_CLIENT_SECRET: AgC7YiRCAVXFd6vme1gih6qRdUa8bYcLNUkwNoR0jA9aKdQs6+TWFDJpeA1xyGeMyTExNAyubSQ9GhszwsSRhygyt5fOdK62ziKii9bk0VtaPxTthgxzPoepjin/SibGNV5raEQ6E8Vrp1+c8LavzugyPB95EhreyCoIroMhPuqctX+0RmoX+ifvwFHrVAmBn7E5HlMnR4xAABwvCEcm7gQSyCO4p4Wy6IWGO7DMKAHRbbO97MSj3UeUtxAoNJrF80p8s0WtwEN6y2Njd6nX4THZ5QttbmVaIQutm0cO00FU358G/Vr7ruFYLzBKJiY3d9qHeBKc6TB40wE/9vNwqMMui3TMtqA/IkWqvcwfL4KE0jzAmp+0Isj1cF6vMvs54xRxO50c43uEZDDg6PrkeJ9wMFW0wBppR6svi/e7XMfrbLzefay7FGn0RcxCMy/eamJomgBJJbh7oINMtAFWDlBaFZIbST6Owg15or8ufO3gkH55g086s3wnDzYJWmgRgZFk7YvGZqbRVQr/v1+3N+FSjz1Rbyly/CB5mDXV3pCL0lu3RCrEB9tzz9JOhm1fIyIniydqWsi5GMdEgdANdd6XC0KwOwKQSUyUsTAkImUZ9SsmmKgllbOzabHqigw8OSss3a269YSR1JVNVcFmRDGgoCT0COjSA3RVfgNKk9HR6W1ScRo599qiKUxS9bBa6aoegR5Uw3zBOCCtkLeL6veVn/CWNzShZ2HI9eSLgYYzxw==
  template:
    metadata:
      creationTimestamp: null
      name: registration-api-secret
      namespace: rm
