apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: resource-catalogue-protected-route
  namespace: rm
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  http:
  - name: resource-catalogue-protected
    match:
      hosts:
        - resource-catalogue-protected.develop.eoepca.org
      paths:
        - /*
    backends:
      - serviceName: resource-catalogue-protected-service
        servicePort: 80
    plugins:
      - name: cors
        enable: true
