apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: resource-catalogue
  namespace: rm
spec:
  http:
  - name: root
    backends:
    - serviceName: vector
      servicePort: 8080
    match:
      hosts:
      - resource-catalogue.apx.develop.eoepca.org
      paths:
      - /
