
resources:
  - resource-catalogue
  - registration-api
  - data-access
  - datacube-access
  - zoo-dru
  - zoo-dru-wes
  - workspace
  - mlops
  - application-quality
  - portal-v1x
  - registration-harvester
  - iam
  - application-hub
  - resource-health
  - openeo-geotrellis
  - openeo-web-editor
  - openeofed
  - notification-automation
  # - identity-service
