apiVersion: batch/v1
kind: CronJob
metadata:
  name: resource-health-bob-custom-consumer-check
  namespace: resource-health
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: OPEN_ID_CONNECT_URL
                  value: "https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
                - name: OPEN_ID_REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: resource-health-bob-offline-secret
                      key: offline_token
                - name: OPEN_ID_CONNECT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: resource-health-iam-client-credentials
                      key: client_id
                - name: OPEN_ID_CONNECT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: resource-health-iam-client-credentials
                      key: client_secret
                - name: OPEN_ID_CONNECT_AUDIENCE
                  value: "account"
                - name: REMOTE_PROTECTED_DOMAIN
                  value: "https://opensearch-cluster-master-headless:9200"
                - name: TLS_NO_VERIFY
                  value: "true"

              image: 'docker.io/eoepca/mitmproxy_oidc:v0.3.0-internal2'
              imagePullPolicy: IfNotPresent
              name: proxy-oidc-sidecar

            - command: ["/usr/bin/bash"]
              args: ["-c", "/app/run_script.sh pytest --export-traces -rP --suppress-tests-failed-exit-code tests.py --user-id bob; ret=$?; curl -s 'http://127.0.0.1:8080/quitquitquit'; exit $ret"]
              env:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: 'https://resource-health-opentelemetry-collector:4317'
                - name: OTEL_EXPORTER_OTLP_CERTIFICATE
                  value: /tls/ca.crt
                - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
                  value: /tls/tls.key
                - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
                  value: /tls/tls.crt
                - name: OTEL_RESOURCE_ATTRIBUTES
                  value: >-
                    k8s.cronjob.name=resource-health-bob-custom-consumer-check,
                    user.id=bob,
                    health_check.name=hourly-custom-data
                #- name: RESOURCE_HEALTH_RUNNER_REQUIREMENTS
                #  value: >-
                #    https://gist.github.com/tilowiklundSensmetry/aa8a28ab9bc432b8a76635a238c9aa11/raw/9dc5847959a909ffbaeb1a9239bbf10ad442266f/requirements.txt
                - name: RESOURCE_HEALTH_RUNNER_SCRIPT
                  value: >-
                    https://gist.github.com/tilowiklundSensmetry/47d5a9bb2a9aa66ca4cfc71ba70814ff/raw/72755d75c4e85dd9ea651e1c963502c4244119f7/test_consuming_custom_data.py
              image: 'docker.io/eoepca/healthcheck_runner:v0.3.0-internal5'
              imagePullPolicy: IfNotPresent
              name: health-check-runner
              volumeMounts:
                - mountPath: /tls
                  name: tls
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: tls
              secret:
                secretName: resource-health-healthchecks-certificate
  
  suspend: false
  schedule: '@daily'